### ISSUE TITLE
Create a shopcart

### ISSUE THREAD

**Issue by huwwww** [nyu-devops-fall2022/shopcarts#1]
**As a** User
 **I need** the ability to create a shopcart
 **So that** I can add products that I want to purchase to the shopcart
   
 ### Details and Assumptions
 * We can create a shopcart if there is no existed one
   
 ### Acceptance Criteria  
   
 ```gherkin
Given no shopcarts exist
When I call `POST /shopcarts`
Then a shopcart will be created and that shopcart will have a unique id
 ```

**Comment by allenpthuang** [comment]
I modified a bit to do the RESTful call `PUT /shopcarts`

**Comment by allenpthuang** [comment]
I'm thinking about the two cases: 1) "create a shopcart without any argument" (`PUT /shopcarts`), and 2) "create a shopcart with a given id/name" (`PUT /shopcarts/foo`).

1. we create a unique id and let Customers know?
2. Customers assign and bind a unique id to their data, and send it to us?
