### ISSUE TITLE
Read a shopcart

### ISSUE THREAD

**Issue by sweta1947** [nyu-devops-fall2022/shopcarts#10]
**As a** User
 **I need** to know details about my shopcart (e.g. total cost)
 **So that** I can shop according to my budget
   
 ### Details and Assumptions
 * Adding or Deleting items in the list updates the total cost accordingly and instantly
 * total cost will be calculated for the unique users' cart independently
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the shopcart has items in it
 When I click 'GET /shopcarts/${shopcartId}'
 Then the details (e.g. total cost) should also be visible

 Given the shopcart items are added/deleted
 When I click 'GET /shopcarts/${shopcartId}'
 Then the updated details (e.g. total cost) should also be visible
 ```

**Comment by allenpthuang** [comment]
I think this one is actually "Read a shopcart" (`GET /shopcarts/{id}`)? I made some changes to this story. Please feel free to comment if there's anything not making senses!
