### ISSUE TITLE
Be able to find items in cart as left in last session

### ISSUE THREAD

**Issue by sweta1947** [nyu-devops-fall2022/shopcarts#14]
**As a** User
 **I need** to find my shopcart prefilled with items filled before 
 **So that** I can order items in cart anytime later whenever I am ready
   
 ### Details and Assumptions
 *  Adding, Deleting, Updating items in shopcart will call the api created for database update for storing the shopcart changes for unique userID

 ### Acceptance Criteria  
   
 ```gherkin
Given the shopcart `foo` does exist
When I call 'GET /shopcarts/foo'
It returns the products in the shopcart
 ```

**Comment by allenpthuang** [comment]
In other words, we need to save states after operations in the database so that we can retrieve them later.

**Comment by allenpthuang** [comment]
Potential duplication to #10? @sweta1947 do you think we can close this one?

**Comment by allenpthuang** [comment]
As per our offline discussion, I'm closing this issue for now. Feel free to reopen it if you have any questions!
