### ISSUE TITLE
Add an item to a shopcart

### ISSUE THREAD

**Issue by yuheng-lu** [nyu-devops-fall2022/shopcarts#4]
**As a** User
**I need** to be able to add a specific item or item(s) from the existing shopcart
**So that** I can put what I would like to check out later in the shopcart

**Assumptions:**
* Every product should have a unique id
* Only the owner of the shopcart can add the item(s). That is to say, we will need authorization.

**Acceptance Criteria**
```
Given that the item does not exist in the given shopcart
When I call 'POST /shopcarts/{shopcartId}/items/{productId}'
Then the item should be added to the shop cart
Given that the item does exist in the given shopcart
When I call 'POST /shopcarts/{shopcartId}/items/{productId}'
The number of items in the shopcart should be increased
```

**Comment by allenpthuang** [comment]
Update the description with endpoints in `/shopcarts/{shopcartId}/items/{productId}`
