### ISSUE TITLE
BDD yml file creation

### ISSUE THREAD

**Issue by sweta1947** [nyu-devops-fall2022/shopcarts#44]
**As a** Developer
 **I need** to create a .github/workflows/bdd.yml file and configure Github Actions
 **So that** test cases run every time someone pushes to the master branch or submits a Pull Request
   
 ### Details and Assumptions
 * [document what you know]
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given [some context]
 When [certain action is taken]
 Then [the outcome of action is observed]
 ```

**Comment by allenpthuang** [comment]
Just a note: do this after Requirement 4 is completed.
