### ISSUE TITLE
Add a single page UI

### ISSUE THREAD

**Issue by sweta1947** [nyu-devops-fall2022/shopcarts#45]
**As a** eCommerce manager
 **I need** find a simple single page UI
 **So that** we can administer the shopcart application
   
 ### Details and Assumptions
 * [document what you know]
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given [some context]
 When [certain action is taken]
 Then [the outcome of action is observed]
 ```

**Comment by allenpthuang** [comment]
Reassigned to @sweta1947
