### ISSUE TITLE
List all items in a shopping cart

### ISSUE THREAD

**Issue by allenpthuang** [nyu-devops-fall2022/shopcarts#9]
**As a** User
 **I need** a function to list items in a shopping cart  
 **So that** I can check them on a webpage before checking out
   
 ### Details and Assumptions
 * Only the owner of a shopping cart can perform this operation
 * Empty shopping cart is a valid shopping cart
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the shopping cart exists
 When I call 'GET /shopcarts/{id}/items'
 Then it should return the list of the items in the shopping cart
 ```

**Comment by allenpthuang** [comment]
Ths should be "Read a shopcart", right?
```GET    /shopcarts/{id}	 <- Read a shopcart```

**Comment by allenpthuang** [comment]
Changed this one to differentiate it from "Read a shopcart".

**Comment by RoubingXia** [comment]
Merged
